const {
  PROFILE_ENDPOINT,
  SERVICE_PORT = 4000,
  SERVICE_PATH = '/', // /midgard/graphql,
  COMPANION_SECRET = 'uploadsecretcompanion',
  COMPANION_DOMAIN = 'localhost:4000',
  COMPANION_DATADIR = '/uppy-tmp',
  COMPANION_AWS_USE_ACCELERATE_ENDPOINT = false,

  COMPANION_AWS_KEY,
  COMPANION_AWS_SECRET,
  COMPANION_AWS_BUCKET,
  COMPANION_AWS_REGION,

  CORS_ORIGIN = 'https://endata-sit.endataclaims.com',
} = process.env

module.exports = {
  PROFILE_ENDPOINT,
  SERVICE_PORT,
  SERVICE_PATH,
  COMPANION_SECRET,
  COMPANION_DOMAIN,
  COMPANION_DATADIR,
  COMPANION_AWS_KEY,
  COMPANION_AWS_SECRET,
  COMPANION_AWS_BUCKET,
  COMPANION_AWS_REGION,
  COMPANION_AWS_USE_ACCELERATE_ENDPOINT,
  CORS_ORIGIN,
}